import { Roboto } from 'next/font/google';
import './globals.css';
import Header from './_components/Header';
import Footer from './_components/Footer';

const roboto = Roboto({ subsets: ['latin'], weight: '400' });

export const metadata = {
  title: 'Online grocery store',
  description: 'Generated by Next',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={roboto.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
